---
- name: Testing andrewrothstein.starship
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'starship --version'
      ansible.builtin.command: /usr/local/bin/starship --version
      changed_when: false
      register: starship_test_output
    - name: Output of 'starship --version'
      ansible.builtin.debug:
        msg: '{{ starship_test_output.stdout }}'
