---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/starship --version
    register: starship_test_output
  - name: starship --version
    debug:
      msg: '{{ starship_test_output.stdout }}'
